version: '3.9'
services:
  db:
    container_name: db
    hostname: db
    image: mysql:8.0
    user: "74:74"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_hbach_template
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - '../database/docker/db/data:/var/lib/mysql'
      - '../database/docker/db/sql:/opt/db/sql'
  site:
    build: .
    container_name: site
    hostname: site
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: db_hbach_template
      # PROJECT_ID: 3
      # PROJECT_CONTENT: "{\"conteudos\":[\"posts\"]}"
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 5555:80
  site_dash:
    build: .
    container_name: site_dash
    hostname: site_dash
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: db_hbach_template
    depends_on:
      - db
    ports:
      - '7777:80'
    volumes:
      - ../modelo-zero-admin:/var/www/html
